---
deployment:
  tasks:
    - export APPPATH=${HOME}/public_html/Cryptere
    - cd ${APPPATH}
    - /usr/local/bin/php artisan optimize:clear
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan route:cache
    - /usr/local/bin/php artisan view:cache
