---
deployment:
  tasks:
    - export APPPATH=/home/fkdzqxmc/cryptere
    - export PUBLICPATH=/home/fkdzqxmc/public_html
    - cd $APPPATH
    - php artisan optimize:clear
    - /bin/rm -rf $PUBLICPATH/build
    - /bin/mkdir -p $PUBLICPATH
    - /bin/cp -R public/build $PUBLICPATH/build
