<?php

/*
|--------------------------------------------------------------------------
| Level Thresholds (100 levels — exponential curve)
|--------------------------------------------------------------------------
|
| Each level requires a minimum XP. The curve uses:
|   min_xp = floor(100 × 1.12^(level − 1))
|
| With lesson xp_reward ≈ 25 and challenge XP ≈ 10, reaching level 100
| requires millions of XP — designed for very long-term progression.
|
| bonus_percent: each level grants 0.1% bonus to point earnings.
|   Level 10 → 1%, Level 50 → 5%, Level 100 → 10%.
|
*/

return [

    'thresholds' => [
        1 => ['min_xp' => 0,         'name' => 'Plaintext Novice',        'bonus_percent' => 0.1],
        2 => ['min_xp' => 112,       'name' => 'Cipher Initiate',         'bonus_percent' => 0.2],
        3 => ['min_xp' => 125,       'name' => 'Cipher Apprentice',       'bonus_percent' => 0.3],
        4 => ['min_xp' => 140,       'name' => 'Bit Shifter',             'bonus_percent' => 0.4],
        5 => ['min_xp' => 157,       'name' => 'Key Wielder',             'bonus_percent' => 0.5],
        6 => ['min_xp' => 176,       'name' => 'Hash Seeker',             'bonus_percent' => 0.6],
        7 => ['min_xp' => 197,       'name' => 'Nonce Finder',            'bonus_percent' => 0.7],
        8 => ['min_xp' => 221,       'name' => 'Block Linker',            'bonus_percent' => 0.8],
        9 => ['min_xp' => 247,       'name' => 'Entropy Scout',           'bonus_percent' => 0.9],
        10 => ['min_xp' => 277,       'name' => 'Substitution Solver',     'bonus_percent' => 1.0],
        11 => ['min_xp' => 310,       'name' => 'Permutation Adept',       'bonus_percent' => 1.1],
        12 => ['min_xp' => 347,       'name' => 'Frequency Analyst',       'bonus_percent' => 1.2],
        13 => ['min_xp' => 388,       'name' => 'Vigenère Breaker',        'bonus_percent' => 1.3],
        14 => ['min_xp' => 435,       'name' => 'Transposition Crafter',   'bonus_percent' => 1.4],
        15 => ['min_xp' => 487,       'name' => 'Diffusion Weaver',        'bonus_percent' => 1.5],
        16 => ['min_xp' => 546,       'name' => 'Confusion Master',        'bonus_percent' => 1.6],
        17 => ['min_xp' => 611,       'name' => 'Feistel Architect',       'bonus_percent' => 1.7],
        18 => ['min_xp' => 684,       'name' => 'Round Key Forger',        'bonus_percent' => 1.8],
        19 => ['min_xp' => 766,       'name' => 'S-Box Designer',          'bonus_percent' => 1.9],
        20 => ['min_xp' => 858,       'name' => 'Block Builder',           'bonus_percent' => 2.0],
        21 => ['min_xp' => 961,       'name' => 'Stream Cipher Adept',     'bonus_percent' => 2.1],
        22 => ['min_xp' => 1076,      'name' => 'Padding Oracle',          'bonus_percent' => 2.2],
        23 => ['min_xp' => 1205,      'name' => 'IV Generator',            'bonus_percent' => 2.3],
        24 => ['min_xp' => 1350,      'name' => 'Mode Selector',           'bonus_percent' => 2.4],
        25 => ['min_xp' => 1512,      'name' => 'CBC Specialist',          'bonus_percent' => 2.5],
        26 => ['min_xp' => 1693,      'name' => 'CTR Operator',            'bonus_percent' => 2.6],
        27 => ['min_xp' => 1896,      'name' => 'GCM Engineer',            'bonus_percent' => 2.7],
        28 => ['min_xp' => 2123,      'name' => 'AEAD Crafter',            'bonus_percent' => 2.8],
        29 => ['min_xp' => 2378,      'name' => 'MAC Validator',           'bonus_percent' => 2.9],
        30 => ['min_xp' => 2664,      'name' => 'Hash Hunter',             'bonus_percent' => 3.0],
        31 => ['min_xp' => 2983,      'name' => 'Collision Seeker',        'bonus_percent' => 3.1],
        32 => ['min_xp' => 3341,      'name' => 'Merkle Builder',          'bonus_percent' => 3.2],
        33 => ['min_xp' => 3742,      'name' => 'Digest Forger',           'bonus_percent' => 3.3],
        34 => ['min_xp' => 4191,      'name' => 'Preimage Resistant',      'bonus_percent' => 3.4],
        35 => ['min_xp' => 4694,      'name' => 'SHA Disciple',            'bonus_percent' => 3.5],
        36 => ['min_xp' => 5257,      'name' => 'HMAC Sentinel',           'bonus_percent' => 3.6],
        37 => ['min_xp' => 5888,      'name' => 'KDF Alchemist',           'bonus_percent' => 3.7],
        38 => ['min_xp' => 6594,      'name' => 'Salt Miner',              'bonus_percent' => 3.8],
        39 => ['min_xp' => 7386,      'name' => 'Argon Temperer',          'bonus_percent' => 3.9],
        40 => ['min_xp' => 8272,      'name' => 'Prime Seeker',            'bonus_percent' => 4.0],
        41 => ['min_xp' => 9265,      'name' => 'Modular Arithmetician',   'bonus_percent' => 4.1],
        42 => ['min_xp' => 10377,     'name' => 'Euler Theorist',          'bonus_percent' => 4.2],
        43 => ['min_xp' => 11622,     'name' => 'RSA Apprentice',          'bonus_percent' => 4.3],
        44 => ['min_xp' => 13017,     'name' => 'Public Key Crafter',      'bonus_percent' => 4.4],
        45 => ['min_xp' => 14579,     'name' => 'Private Key Guardian',    'bonus_percent' => 4.5],
        46 => ['min_xp' => 16328,     'name' => 'Diffie-Hellman Adept',    'bonus_percent' => 4.6],
        47 => ['min_xp' => 18288,     'name' => 'Elliptic Curve Walker',   'bonus_percent' => 4.7],
        48 => ['min_xp' => 20483,     'name' => 'Signature Forger',        'bonus_percent' => 4.8],
        49 => ['min_xp' => 22941,     'name' => 'Certificate Binder',      'bonus_percent' => 4.9],
        50 => ['min_xp' => 25694,     'name' => 'Crypto Analyst',          'bonus_percent' => 5.0],
        51 => ['min_xp' => 28777,     'name' => 'Protocol Designer',       'bonus_percent' => 5.1],
        52 => ['min_xp' => 32230,     'name' => 'TLS Handshaker',          'bonus_percent' => 5.2],
        53 => ['min_xp' => 36098,     'name' => 'Session Key Broker',      'bonus_percent' => 5.3],
        54 => ['min_xp' => 40429,     'name' => 'Perfect Forward Securer', 'bonus_percent' => 5.4],
        55 => ['min_xp' => 45281,     'name' => 'Zero-Knowledge Prover',   'bonus_percent' => 5.5],
        56 => ['min_xp' => 50714,     'name' => 'Commitment Schemer',      'bonus_percent' => 5.6],
        57 => ['min_xp' => 56800,     'name' => 'Oblivious Transferer',    'bonus_percent' => 5.7],
        58 => ['min_xp' => 63616,     'name' => 'Garbled Circuit Weaver',  'bonus_percent' => 5.8],
        59 => ['min_xp' => 71250,     'name' => 'Secret Sharer',           'bonus_percent' => 5.9],
        60 => ['min_xp' => 79800,     'name' => 'Key Master',              'bonus_percent' => 6.0],
        61 => ['min_xp' => 89376,     'name' => 'Threshold Keeper',        'bonus_percent' => 6.1],
        62 => ['min_xp' => 100101,    'name' => 'Multi-Party Computer',    'bonus_percent' => 6.2],
        63 => ['min_xp' => 112113,    'name' => 'Homomorphic Encoder',     'bonus_percent' => 6.3],
        64 => ['min_xp' => 125567,    'name' => 'Lattice Theorist',        'bonus_percent' => 6.4],
        65 => ['min_xp' => 140635,    'name' => 'Ring-LWE Scholar',        'bonus_percent' => 6.5],
        66 => ['min_xp' => 157511,    'name' => 'NTRU Explorer',           'bonus_percent' => 6.6],
        67 => ['min_xp' => 176412,    'name' => 'Code-Based Cryptographer', 'bonus_percent' => 6.7],
        68 => ['min_xp' => 197582,    'name' => 'Isogeny Navigator',       'bonus_percent' => 6.8],
        69 => ['min_xp' => 221292,    'name' => 'Post-Quantum Pioneer',    'bonus_percent' => 6.9],
        70 => ['min_xp' => 247847,    'name' => 'Crypto Sage',             'bonus_percent' => 7.0],
        71 => ['min_xp' => 277589,    'name' => 'Entropy Sovereign',       'bonus_percent' => 7.1],
        72 => ['min_xp' => 310899,    'name' => 'Randomness Oracle',       'bonus_percent' => 7.2],
        73 => ['min_xp' => 348207,    'name' => 'Provable Securer',        'bonus_percent' => 7.3],
        74 => ['min_xp' => 389992,    'name' => 'Indistinguishability Guru', 'bonus_percent' => 7.4],
        75 => ['min_xp' => 436791,    'name' => 'Semantic Securer',        'bonus_percent' => 7.5],
        76 => ['min_xp' => 489206,    'name' => 'CCA Defender',            'bonus_percent' => 7.6],
        77 => ['min_xp' => 547911,    'name' => 'Reduction Master',        'bonus_percent' => 7.7],
        78 => ['min_xp' => 613660,    'name' => 'Hardness Prover',         'bonus_percent' => 7.8],
        79 => ['min_xp' => 687299,    'name' => 'Complexity Theorist',     'bonus_percent' => 7.9],
        80 => ['min_xp' => 769775,    'name' => 'Quantum Resistant',       'bonus_percent' => 8.0],
        81 => ['min_xp' => 862148,    'name' => 'Shor Defier',             'bonus_percent' => 8.1],
        82 => ['min_xp' => 965606,    'name' => 'Grover Evader',           'bonus_percent' => 8.2],
        83 => ['min_xp' => 1081479,   'name' => 'Qubit Entangler',         'bonus_percent' => 8.3],
        84 => ['min_xp' => 1211256,   'name' => 'Superposition Wielder',   'bonus_percent' => 8.4],
        85 => ['min_xp' => 1356607,   'name' => 'Quantum Key Distributor', 'bonus_percent' => 8.5],
        86 => ['min_xp' => 1519400,   'name' => 'BB84 Implementer',        'bonus_percent' => 8.6],
        87 => ['min_xp' => 1701728,   'name' => 'Quantum Channel Securer', 'bonus_percent' => 8.7],
        88 => ['min_xp' => 1905935,   'name' => 'Photon Cipher',           'bonus_percent' => 8.8],
        89 => ['min_xp' => 2134647,   'name' => 'Quantum Entropy Weaver',  'bonus_percent' => 8.9],
        90 => ['min_xp' => 2390805,   'name' => 'Quantum Guardian',        'bonus_percent' => 9.0],
        91 => ['min_xp' => 2677701,   'name' => 'Cryptographic Titan',     'bonus_percent' => 9.1],
        92 => ['min_xp' => 2999025,   'name' => 'Cipher Overlord',         'bonus_percent' => 9.2],
        93 => ['min_xp' => 3358908,   'name' => 'Algorithm Sovereign',     'bonus_percent' => 9.3],
        94 => ['min_xp' => 3761977,   'name' => 'Security Architect',      'bonus_percent' => 9.4],
        95 => ['min_xp' => 4213414,   'name' => 'Unbreakable Cipher',      'bonus_percent' => 9.5],
        96 => ['min_xp' => 4719024,   'name' => 'One-Time Pad Master',     'bonus_percent' => 9.6],
        97 => ['min_xp' => 5285307,   'name' => 'Information Theorist',    'bonus_percent' => 9.7],
        98 => ['min_xp' => 5919544,   'name' => 'Shannon Disciple',        'bonus_percent' => 9.8],
        99 => ['min_xp' => 6629889,   'name' => 'Kerckhoffs Principle',    'bonus_percent' => 9.9],
        100 => ['min_xp' => 7425476,  'name' => 'Cryptographic Deity',     'bonus_percent' => 10.0],
    ],

];
